#normal deployment with service type node port and here which is creating pods fromnginx server image here and /data should be present on host nodes like on both workernodes

apiVersion: v1
kind: Service
metadata:
  name: gvc
  namespace: grras
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: grras
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: test
        hostPath:
           path: /data
           type: Directory
      containers:
      - image: nginx:1.14.2
        name: nginx
        volumeMounts:
           - name: test
             mountPath: /usr/share/nginx/html/
