apiVersion: v1
kind: Service
metadata:
  name: gsvc
  namespace: grras
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 172.17.0.2 
  claimRef:
    name: gvc
    namespace: grras  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvc
  namespace: grras
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: grras
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
       - name: myvol
         persistentVolumeClaim:
           claimName: gvc
      containers:
      - image: nginx:1.14.2
        name: nginx
        volumeMounts:
           - name: myvol
             mountPath: /usr/share/nginx/html/
